myproject/blog/urls.py
from django.urls import path


from blog.views import (ArticleDetail,
                        ArticleList,
                        ArticlePreview,
                        AuthorList,
                        CategoryList, SearchList
                                        )

# from django.conf import settings
# from django.conf.urls.static import static




app_name = 'blog'
urlpatterns = [
    path ('',ArticleList.as_view(),name='home'),
    path ('page/<int:page>' , ArticleList.as_view(), name='home'),
    path ('detail/<slug:slug>' , ArticleDetail.as_view() , name='detail'),
    path ('preview/<int:pk>' , ArticlePreview.as_view() , name='preview'),
    path ('category/<slug:slug>' , CategoryList.as_view() , name='categorylist'),
    path ('category/<slug:slug>/page/<int:page>' , CategoryList.as_view() , name='categorylisti'),
    path ('author/<slug:username>' , AuthorList.as_view() , name='author'),
    path ('search/' , SearchList.as_view() , name='search'),
    path ('category/page/<int:page>' , SearchList.as_view() , name='search'),
]



# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include , re_path
from account.views import Login, Register , activate
urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('blog.urls')),
    path('' ,include('account.urls')),
    path('' ,include('django.contrib.auth.urls')),
    path('login/' ,Login.as_view() ,name="login"),
    path('register/' ,Register.as_view() ,name="register"),
    path('activate/<uidb64>/<token>/',activate , name="activate"),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

myproject/blog/models.py
from django.db import models
from account.models import User
from django.utils import timezone
from django.utils.html import format_html
from django.urls import reverse

#Comment Package
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment

# My Mangers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def published(self):
        return self.filter(status=True)




# Create your models here.

class IpAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آدرس آیپی")
    


class Category(models.Model):
    parent = models.ForeignKey ('self' , on_delete=models.SET_NULL , blank=True , null=True, related_name='childern' ,verbose_name='زیردسته')
    title = models.CharField(max_length=256 , verbose_name='دسته بندی')
    slug = models.CharField(max_length=256 , verbose_name='آدرس دسته بندی', unique=True)
    position = models.IntegerField(verbose_name='پوزیشن')
    status = models.BooleanField(verbose_name='آيا میخواهید نمایش داده شود؟' , default=True)

    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    objects = CategoryManager()



class Article(models.Model):
    CHOOSE_STATUS = (
        ('d' , 'پیش نویس'),         # draft
        ('p' , 'منشر شده'),         # publish
        ('i' , 'در حال بررسی'),     # investigation
        ('b' , 'برگشت داده شده'),   # back
    )
    author = models.ForeignKey(User , on_delete=models.SET_NULL , null=True , verbose_name='نویسنده',related_name='articles')
    title = models.CharField(max_length=100 , verbose_name='عنوان')
    slug = models.CharField(max_length=100 , unique=True , verbose_name='آدرس عنوان')
    category = models.ManyToManyField(Category , related_name='articles' )
    description = models.TextField(verbose_name='محتوا')
    image = models.ImageField(upload_to='image' , verbose_name='عکس')
    publish = models.DateTimeField(default=timezone.now , verbose_name='انتشار')
    status = models.CharField(choices=CHOOSE_STATUS , max_length=1 , verbose_name='وضعیت')
    is_special = models.BooleanField(verbose_name='مقاله ویژه' , default=False)
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IpAddress,related_name="hits" ,blank=True , verbose_name="بازدیدها")
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return self.title

    def str_category(self):
        return ' ,'.join([cat.title for cat in self.category.all()])
    str_category.short_description = 'دسته بندی'


    def image_tag(self):
        return format_html(f'<img src="{self.image.url}" width=100px height=75px>')
    image_tag.short_description = 'عکس'

    

    def get_absolute_url(self):
        return reverse("account:home")
    

    objects = ArticleManager()

    

myproject/blog/views.py
from account.models import User
from django.views.generic import DetailView , ListView
from blog.models import Article, Category
from django.shortcuts import render , get_object_or_404
from account.mixins import ArticleAccessMixin
from blog.models import IpAddress
from django.db.models import Q
# Create your views here.




# def home(request):
#     context = {
#         'articles' : Article.objects.published(),
#         'category' : Category.objects.filter(status = True)
#     }
#     return render(request , 'blog/home.html' , context)

class ArticleList(ListView):
	queryset = Article.objects.published()
	template_name = 'blog/home.html'
	paginate_by = 3




class ArticleDetail(DetailView):
	template_name = 'blog/detail.html'
	def get_object(self):
		slug = self.kwargs.get('slug')
		article = get_object_or_404(Article.objects.published() , slug=slug)
		ip_address = self.request.user.ip_address
		if ip_address not in article.hits.all():
			article.hits.add(ip_address)


		return article

class ArticlePreview(ArticleAccessMixin, DetailView):
	template_name = 'blog/detail.html'
	def get_object(self):
		pk = self.kwargs.get('pk')
		return Article.objects.filter(pk=pk)




class CategoryList(ListView):
	template_name = 'blog/category_list.html'
	paginate_by = 2
	def get_queryset(self):
		global category
		slug = self.kwargs.get('slug')
		category = get_object_or_404(Category.objects.published() , slug=slug)
		return category.articles.published()
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['category'] = category
		return context


class AuthorList(ListView):
	template_name = 'blog/authorlist.html'
	def get_queryset(self):
		global author
		username = self.kwargs.get('username')
		author = get_object_or_404(User, username=username)
		return author.articles.published()
	def get_context_data(self , **kwargs):
		context = super().get_context_data(**kwargs)
		context['author'] = author
		return context




class SearchList(ListView):
	template_name = 'blog/searchlist.html'
	paginate_by = 1
	def get_queryset(self): # new
		search = self.request.GET.get('q')
		return Article.objects.filter(description__icontains=search)

	def get_context_data(self , **kwargs):
		context = super().get_context_data(**kwargs)
		context['search'] = self.request.GET.get('q')
		return context



		

	   

myproject/comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

myproject/templates/blog/authorlist.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}
{% block main %}
<section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image: url({% static 'blog/assets/img/slide/slide-1.jpg' %});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown">خوش آمدید به <span>{% title %}</span></h2>
                <p class="animate__animated animate__fadeInUp">علیرضا دانایی </p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item" style="background-image: url({% static 'blog/assets/img/slide/slide-2.jpg' %});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item" style="background-image: url({% static 'blog/assets/img/slide/slide-3.jpg' %});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>

      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Us Section ======= -->
    {% for article in object_list %}
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row no-gutters">
          <div class="col-lg-6 video-box">
            <img src="{{article.image.url}}" class="img-fluid" alt="" style="height: 500px; width: 100%;">
            <!-- <a href="#" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a> -->
          </div>

          <div class="col-lg-6 d-flex flex-column justify-content-center about-content">

            <div class="section-title">
              <h2><a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a></h2>
              <p>{{article.description|truncatewords:30}}</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-fingerprint"></i></div>
              <h4 class="title"><a href="">نویسنده</a></h4>
              <p class="description">{{article.author.get_full_name}}</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-gift"></i></div>
              <h4 class="title"><a href="">Nemo Enim</a></h4>
              <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
            </div>

          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->
    {% endfor %}

    <div class="row no-gutters">
      <div class="col-lg-6">
        <nav aria-label="Page navigation example" style="float: left;">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:home' page_obj.previous_page_number %}">Previous</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:home' page_obj.next_page_number %}">Next</a></li>
            {% endif %}
          </ul>
        </nav>
        </div>
    </div>
    

    <!-- ======= Contact Us Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact Us</h2>
        </div>

        <div class="row">

          <div class="col-lg-6 d-flex" data-aos="fade-up">
            <div class="info-box">
              <i class="bx bx-map"></i>
              <h3>Our Address</h3>
              <p>A108 Adam Street, New York, NY 535022</p>
            </div>
          </div>

          <div class="col-lg-3 d-flex" data-aos="fade-up" data-aos-delay="100">
            <div class="info-box">
              <i class="bx bx-envelope"></i>
              <h3>Email Us</h3>
              <p>info@example.com<br>contact@example.com</p>
            </div>
          </div>

          <div class="col-lg-3 d-flex" data-aos="fade-up" data-aos-delay="200">
            <div class="info-box ">
              <i class="bx bx-phone-call"></i>
              <h3>Call Us</h3>
              <p>+1 5589 55488 55<br>+1 6678 254445 41</p>
            </div>
          </div>

          <div class="col-lg-12" data-aos="fade-up" data-aos-delay="300">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-lg-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-lg-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
          </div>

        </div>

      </div>
    </section><!-- End Contact Us Section -->

  </main><!-- End #main -->
  {% endblock %}

myproject/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load base_tags %}
{% block main %}
<section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image: url({% static 'blog/assets/img/slide/slide-1.jpg' %});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown">خوش آمدید به <span>{% title %}</span></h2>
                <p class="animate__animated animate__fadeInUp">علیرضا دانایی </p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item" style="background-image: url({% static 'blog/assets/img/slide/slide-2.jpg' %});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item" style="background-image: url({% static 'blog/assets/img/slide/slide-3.jpg' %});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
                <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
                <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Read More</a>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>

      </div>
    </div>
  </section><!-- End Hero -->
  <div class="alert alert-primary mt-5 text-center fs-2" role="alert">
    دسته بندی : {{category.title}}
  </div>

  <main id="main">

    <!-- ======= About Us Section ======= -->
    {% for article in object_list %}
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row no-gutters">
          <div class="col-lg-6 video-box">
            <img src="{{article.image.url}}" class="img-fluid" alt="" style="height: 500px; width: 100%;">
            <!-- <a href="#" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a> -->
          </div>

          <div class="col-lg-6 d-flex flex-column justify-content-center about-content">

            <div class="section-title">
              <h2><a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a></h2>
              <p>{{article.description|truncatewords:30}}</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-fingerprint"></i></div>
              <h4 class="title"><a href="#">نویسنده</a></h4>
              <p class="description">{{article.author.get_full_name}}</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-gift"></i></div>
              <h4 class="title"><a href="">دسته بندی ها</a></h4>
              
              <p class="description">#{{article.str_category}}</p>
            </div>

          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->
    {% endfor %}
    
    
    <div class="row no-gutters">
      <div class="col-lg-6">
        <nav aria-label="Page navigation example" style="float: left;">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:categorylisti' category.slug page_obj.previous_page_number %}">Previous</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:categorylisti' category.slug page_obj.next_page_number %}">Next</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
    

    <!-- ======= Contact Us Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact Us</h2>
        </div>

        <div class="row">

          <div class="col-lg-6 d-flex" data-aos="fade-up">
            <div class="info-box">
              <i class="bx bx-map"></i>
              <h3>Our Address</h3>
              <p>A108 Adam Street, New York, NY 535022</p>
            </div>
          </div>

          <div class="col-lg-3 d-flex" data-aos="fade-up" data-aos-delay="100">
            <div class="info-box">
              <i class="bx bx-envelope"></i>
              <h3>Email Us</h3>
              <p>info@example.com<br>contact@example.com</p>
            </div>
          </div>

          <div class="col-lg-3 d-flex" data-aos="fade-up" data-aos-delay="200">
            <div class="info-box ">
              <i class="bx bx-phone-call"></i>
              <h3>Call Us</h3>
              <p>+1 5589 55488 55<br>+1 6678 254445 41</p>
            </div>
          </div>

          <div class="col-lg-12" data-aos="fade-up" data-aos-delay="300">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-lg-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-lg-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
          </div>

        </div>

      </div>
    </section><!-- End Contact Us Section -->

  </main><!-- End #main -->
  {% endblock %}

myproject/templates/blog/detail.html
{% extends 'blog/base.html'%}
{% load static %}
{% load comment_tags %}
{% load ratings %}


{% block main %}

<section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image:url({{article.image.url}});">
            <div class="carousel-container">
              <div class="carousel-content container">
                <h2 class="animate__animated animate__fadeInDown text-center">{{object.title}}</h2>
                <div class="text-center">{% ratings article %}</div>
                <div class="text-center" style="color: red;">بازدید ها :{{object.hits.count}}</div>
                <!-- <p class="animate__animated animate__fadeInUp ">{{article.description|safe|truncatewords:15}}</p> -->
                
              </div>
            </div>
          </div>
        </div>
     </div>
    </div>
</section>



    <section id="about " class="about">
      <div class="container " data-aos="fade-up">

        <!-- <div class="row no-gutters">
          <div class="col-lg-6 video-box">
            <img src="{{article.image.url}}" class="img-fluid" alt="" style="height: 500px; width: 100%;">
            <a href="#" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a> 
          </div> -->

          <div class="col-lg-12 ">

            <div class="section-title " >
              <h2>{{object.title}}</h2>
              {% if article.is_special %}
                {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                
                <div style="text-align: right;">
                  <p>{{object.description|safe}}</p>
                </div>
                
                {% else %}
                <p>برای دیدن مقاله لطفا <a href="#">اشتراک ویژه</a> خریداری کنید</p>
                {% endif %}
                {% else %}
                <p>{{object.description|safe}}</p>
              {% endif %}
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-fingerprint"></i></div>
              <h4 class="title"><a href="">Lorem Ipsum</a></h4>
              <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
            </div>

            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="bx bx-gift"></i></div>
              <h4 class="title"><a href="">Nemo Enim</a></h4>
              <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
              {% render_comments article request %}  
              {% include_bootstrap %}
            </div>

          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->


{% endblock %}